FROM spcleth/praas:process-python
ARG example

ADD ${example}/ /function
RUN /bin/bash /function/install.sh

ADD configure.py /function
ADD install.py /function
RUN /function/install.py /function \
    && /function/configure.py /function/functions.json.in /function/functions.json /function \
    && rm /function/functions.json.in \
    && rm /function/configure.py \
    && rm /function/install.py \
    && rm /function/install.sh

